@echo off
echo Starting Smart Campus Server...
echo Installing dependencies if needed...
pip install -r requirements.txt
echo.
echo Initializing database...
python -m flask --app app init-db
echo.
echo Launching Application...
python run.py
pause
